target ‘MuBan’ do

platform :ios, '7.0'

pod 'AFNetworking', '2.6.3'
pod 'MagicalRecord'
pod 'MJRefresh', '~> 3.1.12'
pod 'ZipArchive', '~> 1.4.0'
pod 'FMDB', '2.5'
pod 'JSPatch'
pod 'BlocksKit'
pod 'DZNEmptyDataSet'
pod 'Masonry'
pod 'LKDBHelper'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'WebViewJavascriptBridge'

end
