inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target ‘MuBan’ do

platform :ios, '8.0'

pod 'AFNetworking', '2.6.3'
pod 'MagicalRecord'
pod 'MJRefresh', '~> 3.1.12'
pod 'ZipArchive', '~> 1.4.0'
pod 'FMDB', '2.5'
pod 'JSPatch'
pod 'BlocksKit'
pod 'DZNEmptyDataSet'
pod 'Masonry'
pod 'LKDBHelper'
pod 'SDWebImage'
pod 'IQKeyboardManager'
pod 'WebViewJavascriptBridge'
pod 'NerdyUI', :git => 'https://github.com/nerdycat/NerdyUI.git'
pod 'TLYShyNavBar'
pod 'IDMPhotoBrowser'
pod 'DACircularProgress'
pod 'pop'
pod 'RTRootNavigationController'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = "NO"
        end
    end
end
